### PR TITLE
MADE CHANGES IN THE CONTROLLER'S WHICH  I HAVE ADDED IN THE DESCRIPTION

### PR DESCRIPTION
**Pull request by AyeshaSidra123**
MADE CHANGES IN  : 
       modified:   Natural_API/Controllers/DistributorController.cs
        modified:   Natural_API/Controllers/ExecutiveController.cs
        modified:   Natural_API/Mapping/MappingProfile.cs
        deleted:    Natural_API/Resources/DistributorResource.cs
        modified:   Natural_Core/IRepositories/IDistributorRepository.cs
        modified:   Natural_Core/IRepositories/IExecutiveRepository.cs
        modified:   Natural_Core/IServices/IDistributorService.cs
        modified:   Natural_Core/Models/Distributor.cs
        modified:   Natural_Data/NaturalsContext.cs
        modified:   Natural_Data/Repositories/DistributorRepository.cs
        modified:   Natural_Data/Repositories/ExecutiveRepository.cs
        modified:   Natural_Services/DistributorService.cs

### CODE REVIEW

**Review by ManojKumarReddy17 — APPROVED** [review]
Code Looks Good

**Comment by RohithReddy72** [comment]
okay?

**Review by Reddykumari123 — APPROVED** [review]
looks good

**Review by RohithReddy72 — APPROVED** [review]
OkayOkay

**Pull request merged**
